//! WebSocket event bus — the live stream the chat UI subscribes to.
//!
//! Wire shape matches `spec/asyncapi.yaml`:
//!
//! - `chat.message_inbound` / `chat.message_outbound` — user and agent text
//! - `chat.token_delta` — streaming assistant tokens
//! - `agent.tool_use` / `agent.tool_result` — every tool call
//! - `conversation.phase_changed` — FSM transitions
//! - `alert.*` — operational alerts
//!
//! Publishers call [`broadcast`] with a typed payload; the WebSocket
//! handler ([`stream_handler`]) forwards serialized events to every
//! connected subscriber.
//!
//! **No cloud dependencies.** `tokio::sync::broadcast` in-process only.

use axum::extract::State;
use axum::extract::ws::{Message, WebSocket, WebSocketUpgrade};
use axum::response::IntoResponse;
use serde::{Deserialize, Serialize};
use tokio::sync::broadcast;
use tracing::{debug, warn};

use crate::state::AppState;

/// Every event surface-able to the UI. Additive — new variants land
/// without breaking subscribers since the UI tolerates unknown kinds.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum UiEvent {
    /// Heartbeat so the client can detect dead connections.
    Ping {
        ts: i64,
    },

    /// User sent a message to a conversation.
    ChatMessageInbound {
        conversation_id: String,
        seq: i64,
        text: String,
        sender: Option<String>,
    },
    /// Agent text reply (full, non-streaming).
    ChatMessageOutbound {
        conversation_id: String,
        seq: i64,
        text: String,
    },
    /// Incremental token during a streaming turn.
    ChatTokenDelta {
        conversation_id: String,
        text: String,
    },

    AgentToolUse {
        conversation_id: String,
        seq: i64,
        tool_name: String,
        ordinal: u32,
    },
    AgentToolResult {
        conversation_id: String,
        seq: i64,
        ordinal: u32,
        ok: bool,
    },

    /// Live "what's the agent doing right now" pulse, fired the
    /// instant the runner emits a tool-call request and again when
    /// it resolves. Carries a human-readable `label` (e.g.
    /// "Searching the web for 'paris weather forecast today'")
    /// generated by `chats::humanise_tool_call` so the SPA's loader
    /// shows progress without having to know about every tool's
    /// args shape.
    ///
    /// Distinct from `AgentToolUse` (which is the persisted
    /// `tool_use` event-log row's broadcast) because the
    /// activity-pulse fires BEFORE the dispatch round-trip and
    /// again AFTER — `AgentToolUse` only lands once the runner
    /// commits the model_turn at end-of-turn.
    AgentToolActivity {
        conversation_id: String,
        /// Raw tool name (e.g. `web_search`, `calendar.list_events`).
        /// Drives icon selection on the SPA side.
        tool_name: String,
        /// Operator-facing one-liner. Always English-ish, generated
        /// from (tool_name, args) by `humanise_tool_call`. Falls
        /// back to "Running <tool_name>…" for tools without a
        /// custom humaniser entry.
        label: String,
        /// `"started"` when the agent issued the call;
        /// `"finished"` when the result is back (regardless of
        /// success — the SPA's loader just clears either way).
        status: String,
    },

    ConversationPhaseChanged {
        conversation_id: String,
        phase: String,
    },

    /// Fired by the sidecar supervisor when a supervised sidecar's
    /// observed status changes (Stopped → Starting → Healthy →
    /// CrashLooping → ...). The SPA's sidecars page uses these to
    /// keep its row badges live without polling. `name` is the
    /// sidecar's globally-unique service-name identifier; `status`
    /// is the `Debug` rendering of `ServiceStatus` so a future
    /// CrashLooping variant carries `restart_count` along for free.
    SidecarStatusChanged {
        name: String,
        status: String,
    },

    AlertFired {
        alert_id: String,
        severity: String,
        source: String,
        title: String,
    },
    AlertResolved {
        alert_id: String,
    },

    /// A new pending approval landed on the controller's queue. Today
    /// the only producer is the cold-contact path (a non-trusted
    /// principal sent the agent a message and we parked the
    /// conversation in `AwaitingTrustDecision`); future producers
    /// (Rule-of-Two breach, sensitive-tool-call) follow the same
    /// shape. The SPA's `ApprovalWatcher` listens for this and
    /// re-fetches `/api/admin/approvals` to refresh the sidebar
    /// badge in real-time — the same shape `AlertFired` has for the
    /// brand-status indicator.
    ApprovalCreated {
        approval_id: String,
        conversation_id: String,
    },
    /// A pending approval was acted on (Trust / TrustLimited / Block /
    /// IgnoreOnce / ClaimAsMe — any verb that flips the approval out
    /// of `UnknownPending`). Triggers the same SPA refresh.
    ApprovalResolved {
        approval_id: String,
        conversation_id: String,
    },

    /// A routine run-history row's status changed (queued, picked up,
    /// finished). Drives live updates in the Settings → Routines
    /// run-history drawer so the operator doesn't have to refresh
    /// after a manual fire or to watch a scheduled fire complete.
    RoutineRunChanged {
        routine_id: String,
        run_id: String,
        /// Mirrors `RoutineRunStatus` — one of "Pending" | "Success"
        /// | "Failed" | "Skipped".
        status: String,
    },

    /// A durable child-agent run changed state. The Agents page uses this
    /// event to rehydrate the selected run list without polling.
    AgentRunChanged {
        agent_id: String,
        run_id: String,
        status: String,
    },

    // ---- Phase 13.B — voice session lifecycle ----------------
    /// A voice session opened — first frame for the given session
    /// id arrived. Consumed by the SPA to render a "live mic" UX.
    VoiceSessionStarted {
        session: String,
        codec: String,
        sample_rate: u32,
    },
    /// A voice session ended either because the operator hit stop
    /// or because the server's stale-session reaper aged it out.
    VoiceSessionEnded {
        session: String,
        /// One of "operator_stopped" | "stale_reap" |
        /// "transport_closed".
        reason: String,
    },
    /// Streaming partial transcript. The Whisper adapter (Phase
    /// 13.C) feeds these as text accumulates; SPA renders them
    /// inline with the typing-indicator UX.
    VoiceTranscript {
        session: String,
        seq: u32,
        text: String,
        /// True when the segment is the final transcript (the
        /// endpointer fired and the LLM call is being dispatched).
        /// SPA uses this to commit the partial to the chat log.
        is_final: bool,
    },
    /// Outbound TTS audio chunk for the SPA to play. Phase 13.C
    /// fills these with real Kokoro output; today this variant
    /// exists so the SPA's WS handler can be wired ahead of the
    /// adapter landing.
    VoiceAudioOutbound {
        session: String,
        seq: u32,
        /// Codec the bytes are encoded in. SPA's audio pipeline
        /// picks the right MediaSource decoder.
        codec: String,
        /// base64 of the codec payload — keeps the WS event JSON
        /// inspectable in dev tools. Binary out lands when the
        /// SPA's audio pipeline is ready for raw frames.
        audio_b64: String,
    },
    /// Operator (or VAD) interrupted the agent mid-response. The
    /// SPA flushes any in-flight audio playback; the runner halts
    /// the LLM stream and TTS synthesis.
    VoiceInterrupted {
        session: String,
        /// One of "operator_barge_in" | "vad_speech_detected".
        reason: String,
    },

    // ---- C4 — generic Card primitive (deep research, future
    // shell-session / file-pipeline tools all share this surface) ---
    /// A new Card is being opened on the conversation. Carries the
    /// full opened payload so the SPA's card-store can `fromOpened`
    /// without an extra fetch. Mirrors `EventKind::CardOpened` from
    /// the event log; the WS surface is the live channel + the log
    /// is the durable source of truth.
    CardOpened {
        conversation_id: String,
        card_id: String,
        /// Lowercase kind: "research" / "long_running_task" / etc.
        card_kind: String,
        title: String,
        summary: String,
        state: Option<String>,
        details: serde_json::Value,
        actions: serde_json::Value,
        committed_at: i64,
        /// 2026-05-03 — assigned `state_events.seq` so the SPA can
        /// place the card inline in the chat-thread timeline at
        /// the same position it occupies in the durable event log
        /// (instead of falling back to a synthetic timestamp-based
        /// sortKey that always pinned cards to the bottom).
        event_seq: i64,
    },

    /// A Card progressed — partial update (every field optional;
    /// projection merges populated fields onto the live row). The
    /// SPA's per-kind renderer reads `details` to paint kind-specific
    /// state (e.g. ResearchCard reads `details.notes` for the
    /// per-sub-query badges).
    CardProgressed {
        conversation_id: String,
        card_id: String,
        state: Option<String>,
        progress: Option<f32>,
        phase: Option<String>,
        details: Option<serde_json::Value>,
        actions: Option<serde_json::Value>,
        summary: Option<String>,
        committed_at: i64,
        event_seq: i64,
    },

    /// A Card reached its terminal state. SPA flips inline-render
    /// from "live" to "summary + actions"; transports may invoke
    /// `send_file` if `attachment_id` is populated (C5 wires that).
    CardClosed {
        conversation_id: String,
        card_id: String,
        state: String,
        summary: String,
        details: Option<serde_json::Value>,
        attachment_id: Option<String>,
        error: Option<String>,
        committed_at: i64,
        event_seq: i64,
    },

    /// A deep-research job paused waiting on operator clarification.
    /// Sister event to the `CardProgressed{phase: AwaitingInput}` the
    /// SPA renders — this one is consumed by the server-side
    /// `clarification_listener`, which wakes the agent in the
    /// affected conversation so it can relay the question back to
    /// the user. Kept distinct from `CardProgressed` so the listener
    /// can subscribe with a narrow filter rather than projecting
    /// every card update.
    ///
    /// 2026-05-03 (rev 7): replaces the polling-on-research_start
    /// fast path. The agent's tool turn now returns immediately;
    /// the listener fires a follow-up agent turn when the planner
    /// decides clarification is needed.
    ResearchAwaitingInput {
        conversation_id: String,
        job_id: String,
        question: String,
    },
}

/// Broadcast channel capacity. Lagging subscribers drop the oldest
/// events (broadcast's default behavior), which is fine — the UI uses
/// the event log for canonical state.
const CHANNEL_CAPACITY: usize = 256;

/// Handle that publishers use to fan-out `UiEvent`s to every live
/// WebSocket subscriber.
#[derive(Clone, Debug)]
pub struct EventBus {
    tx: broadcast::Sender<UiEvent>,
}

impl EventBus {
    pub fn new() -> Self {
        let (tx, _rx) = broadcast::channel(CHANNEL_CAPACITY);
        Self { tx }
    }

    /// Broadcast an event. Swallows "no receivers" since it's expected
    /// to happen before any UI connects.
    pub fn publish(&self, ev: UiEvent) {
        let _ = self.tx.send(ev);
    }

    /// Create a new subscriber. Returns the receiver only; callers must
    /// hold it for the duration they want to observe events.
    pub fn subscribe(&self) -> broadcast::Receiver<UiEvent> {
        self.tx.subscribe()
    }

    /// Current subscriber count — useful for health probes.
    pub fn subscriber_count(&self) -> usize {
        self.tx.receiver_count()
    }
}

impl Default for EventBus {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// WebSocket handler
// ---------------------------------------------------------------------------

/// `GET /api/stream` — upgrades to a WebSocket that pushes every
/// [`UiEvent`] to the connected client. Accepts incoming text messages
/// only for pings (ignored in Phase 1; reserved for future bidirectional
/// control messages).
pub async fn stream_handler(
    State(state): State<AppState>,
    ws: WebSocketUpgrade,
) -> impl IntoResponse {
    let bus = state.events.clone();
    let voice = state.voice_sessions.clone();
    let runtime = state.voice_runtime.clone();
    ws.on_upgrade(move |socket| handle_socket(socket, bus, voice, runtime))
}

async fn handle_socket(
    mut socket: WebSocket,
    bus: EventBus,
    voice: crate::voice_session::VoiceSessionRegistry,
    runtime: crate::voice_runtime::VoiceRuntime,
) {
    let mut rx = bus.subscribe();
    debug!(
        "ws stream connected; subscribers now {}",
        bus.subscriber_count()
    );

    // Send an initial ping so the client knows the stream is live.
    let _ = socket
        .send(Message::Text(
            serde_json::to_string(&UiEvent::Ping {
                ts: chrono::Utc::now().timestamp(),
            })
            .unwrap_or_else(|_| "{}".into())
            .into(),
        ))
        .await;

    // Phase 13.D audit closure — track every voice session this WS
    // opens so we can drop them on disconnect. Without this, a tab
    // close mid-utterance leaves the session in the registry until
    // the 30-second reaper sweeps it; meanwhile TTS keeps streaming
    // VoiceAudioOutbound events to a dead WS and the Whisper /
    // Kokoro reqwest pools sit open. A `HashSet` is overkill — the
    // operator only opens one mic at a time today, so the typical
    // size is 0 or 1, but the structure supports a future
    // multi-source UX.
    let mut owned_sessions: std::collections::HashSet<String> = std::collections::HashSet::new();

    loop {
        tokio::select! {
            ev = rx.recv() => match ev {
                Ok(ui_ev) => {
                    let payload = match serde_json::to_string(&ui_ev) {
                        Ok(s) => s,
                        Err(e) => {
                            warn!("ws serialize failed: {e}");
                            continue;
                        }
                    };
                    if socket.send(Message::Text(payload.into())).await.is_err() {
                        break;
                    }
                }
                Err(broadcast::error::RecvError::Lagged(n)) => {
                    warn!("ws lagged by {n} events; client will see gap");
                    // keep going; client should re-hydrate from the event log
                }
                Err(broadcast::error::RecvError::Closed) => break,
            },
            incoming = socket.recv() => match incoming {
                Some(Ok(Message::Close(_))) | None => break,
                Some(Ok(Message::Binary(bytes))) => {
                    // Phase 13.B — parse the framing header, then
                    // hand the chunk to the voice-session registry.
                    // Phase 13.C — the registry's released chunks
                    // are forwarded into `voice_runtime.ingest_chunks`,
                    // which feeds the real Whisper adapter.
                    match crate::voice_frame::parse_frame(&bytes) {
                        Ok((header, payload)) => {
                            let outcome = voice.observe_frame(&header, payload).await;
                            if outcome.session_opened {
                                owned_sessions.insert(header.session.clone());
                            }
                            voice.publish_outcome(&header, &outcome);
                            if !outcome.released.is_empty() {
                                runtime.ingest_chunks(&outcome.released).await;
                            }
                        }
                        Err(e) => {
                            warn!(
                                bytes = bytes.len(),
                                "ws voice frame parse failed: {e}"
                            );
                        }
                    }
                }
                Some(Ok(Message::Text(text))) => {
                    // Phase 13.C / 13.D — voice control messages.
                    // Schema:
                    //   {"op":"voice_stop","session":"…"}
                    //   {"op":"voice_interrupt","session":"…"}
                    // Anything else is ignored. The control surface
                    // is intentionally tiny so a malformed message
                    // can't tear down the WS.
                    let closed = handle_voice_control(&text, &voice, &runtime).await;
                    // The voice_stop branch closes its own session;
                    // remove it from the per-WS tracking set so we
                    // don't double-close on disconnect.
                    if let Some(session_id) = closed {
                        owned_sessions.remove(&session_id);
                    }
                }
                Some(Ok(_)) => {} // ignore other client→server traffic
                Some(Err(e)) => {
                    warn!("ws recv error: {e}");
                    break;
                }
            }
        }
    }

    // Phase 13.D audit closure — sweep every voice session this WS
    // owned. `voice_stop` already drained the matching session from
    // the set, so this only fires for the disconnect path (tab
    // close / network drop / server shutdown).
    if !owned_sessions.is_empty() {
        debug!(
            "ws stream disconnected; cleaning up {} owned voice session(s)",
            owned_sessions.len()
        );
        for session_id in owned_sessions {
            voice.end_session(&session_id, "transport_closed").await;
            runtime.drop_session(&session_id).await;
        }
    }
    debug!("ws stream disconnected");
}

/// Phase 13.C/D — parse + dispatch a voice-control text message.
/// Public for unit testing; the WS handler calls it directly.
///
/// Returns `Some(session_id)` when the message closed a session
/// (i.e. `voice_stop`) so the caller's per-WS owned-session tracker
/// can drop it without double-closing. Returns `None` for
/// `voice_interrupt`, malformed input, and unknown ops.
pub async fn handle_voice_control(
    text: &str,
    voice: &crate::voice_session::VoiceSessionRegistry,
    runtime: &crate::voice_runtime::VoiceRuntime,
) -> Option<String> {
    let parsed: serde_json::Value = match serde_json::from_str(text) {
        Ok(v) => v,
        Err(_) => return None, // not JSON — silently ignore (could be a future text op)
    };
    let op = parsed.get("op").and_then(|v| v.as_str()).unwrap_or("");
    let session = parsed.get("session").and_then(|v| v.as_str()).unwrap_or("");
    if session.is_empty() {
        return None;
    }
    match op {
        "voice_stop" => {
            // Operator toggled mic off. Flush STT, then run the
            // agent reply path. The agent callback is wired in the
            // chat layer (Phase 13.C+); for v1 we stub with the
            // identity transcript so the pipeline is observable
            // end-to-end without yet plumbing into the chat router.
            // The real agent_reply hookup lands in 13.D.
            //
            // Panic safety (audit closure): the spawned task runs
            // finalize_utterance + cleanup. A panic in either would
            // strand the registry session forever without the
            // VoiceStopGuard below — its Drop impl always calls
            // end_session + drop_session, so the cleanup path
            // survives any panic in finalize_utterance or in a
            // future real `agent_reply` callback.
            let session_id = session.to_owned();
            let runtime_for_finalize = runtime.clone();
            let guard = VoiceStopGuard {
                session_id: session_id.clone(),
                voice: voice.clone(),
                runtime: runtime.clone(),
            };
            tokio::spawn(async move {
                let _guard = guard;
                runtime_for_finalize
                    .finalize_utterance(&session_id, |transcript| async move {
                        // Placeholder: echo the transcript so the
                        // SPA can verify the round-trip. Phase 13.D
                        // wires this to the runner / chat path.
                        format!("you said: {transcript}")
                    })
                    .await;
                // _guard drops here on the happy path → end_session
                // + drop_session run regardless of whether the
                // finalize_utterance future panicked.
            });
            return Some(session.to_owned());
        }
        "voice_interrupt" => {
            // Operator (or future server-side VAD) interrupted the
            // agent's reply mid-stream.
            runtime.interrupt(session, "operator_barge_in").await;
        }
        _ => {}
    }
    None
}

/// Phase 13.D audit closure — RAII guard that closes a voice
/// session in its Drop impl. Used by the `voice_stop` spawn so a
/// panic inside `finalize_utterance` (or a future real chat-path
/// callback) doesn't strand the session in the registry.
///
/// The Drop impl spawns its own background task because Drop is
/// sync but `end_session` / `drop_session` are async. The guard's
/// fields are cheap clones (`Arc` underneath) so the spawn doesn't
/// require any allocation outside the Arc itself.
struct VoiceStopGuard {
    session_id: String,
    voice: crate::voice_session::VoiceSessionRegistry,
    runtime: crate::voice_runtime::VoiceRuntime,
}

impl Drop for VoiceStopGuard {
    fn drop(&mut self) {
        let session_id = std::mem::take(&mut self.session_id);
        let voice = self.voice.clone();
        let runtime = self.runtime.clone();
        tokio::spawn(async move {
            voice.end_session(&session_id, "operator_stopped").await;
            runtime.drop_session(&session_id).await;
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn bus_publishes_to_subscribers() {
        let bus = EventBus::new();
        let mut rx = bus.subscribe();
        bus.publish(UiEvent::Ping { ts: 42 });
        let got = rx.recv().await.unwrap();
        match got {
            UiEvent::Ping { ts } => assert_eq!(ts, 42),
            other => panic!("wrong kind: {other:?}"),
        }
    }

    #[tokio::test]
    async fn bus_tolerates_no_subscribers() {
        let bus = EventBus::new();
        // No panic, no error.
        bus.publish(UiEvent::Ping { ts: 1 });
    }

    #[test]
    fn ui_event_tag_is_snake_case() {
        let e = UiEvent::ChatMessageInbound {
            conversation_id: "c".into(),
            seq: 1,
            text: "hi".into(),
            sender: None,
        };
        let s = serde_json::to_string(&e).unwrap();
        assert!(s.contains("\"kind\":\"chat_message_inbound\""));
    }

    #[tokio::test]
    async fn subscriber_count_tracks_live_subscribers() {
        let bus = EventBus::new();
        assert_eq!(bus.subscriber_count(), 0);
        let _a = bus.subscribe();
        let _b = bus.subscribe();
        assert_eq!(bus.subscriber_count(), 2);
        drop(_a);
        assert_eq!(bus.subscriber_count(), 1);
    }

    // ---- Phase 13.C — voice control message dispatch -------------

    use crate::voice_runtime::{SttFactory, TtsFactory, VoiceRuntime};
    use crate::voice_session::VoiceSessionRegistry;
    use execlaw_voice_pipeline::traits::{MockStt, MockTts, TtsClient};
    use std::sync::Arc;
    use std::time::Duration;

    fn mock_runtime(bus: EventBus) -> VoiceRuntime {
        let stt: SttFactory =
            Arc::new(|| Box::new(MockStt::new(Vec::new(), "transcribed!".to_owned())));
        let tts: TtsFactory =
            Arc::new(|| (Box::new(MockTts::default()) as Box<dyn TtsClient>, None));
        VoiceRuntime::new(bus, stt, tts)
    }

    #[tokio::test]
    async fn handle_voice_control_ignores_non_json_text() {
        let bus = EventBus::new();
        let voice = VoiceSessionRegistry::new(bus.clone());
        let runtime = mock_runtime(bus);
        // Should not panic.
        handle_voice_control("not json", &voice, &runtime).await;
    }

    #[tokio::test]
    async fn handle_voice_control_ignores_unknown_op() {
        let bus = EventBus::new();
        let voice = VoiceSessionRegistry::new(bus.clone());
        let runtime = mock_runtime(bus);
        handle_voice_control(r#"{"op":"voice_yodel","session":"s1"}"#, &voice, &runtime).await;
        // No assertion target — pass if no panic + no event. The
        // shape of "did nothing" is captured by the lack of side
        // effects in subsequent tests.
    }

    #[tokio::test]
    async fn handle_voice_control_drops_messages_without_session() {
        let bus = EventBus::new();
        let voice = VoiceSessionRegistry::new(bus.clone());
        let runtime = mock_runtime(bus);
        handle_voice_control(r#"{"op":"voice_stop"}"#, &voice, &runtime).await;
    }

    #[tokio::test]
    async fn voice_interrupt_op_publishes_voice_interrupted() {
        let bus = EventBus::new();
        let mut rx = bus.subscribe();
        let voice = VoiceSessionRegistry::new(bus.clone());
        let runtime = mock_runtime(bus);
        // Need a live runtime session for interrupt to do anything.
        // Create one by ingesting a chunk first.
        let chunk = crate::voice_session::OrderedAudioChunk {
            session: "s1".into(),
            seq: 0,
            codec: "pcm16le".into(),
            sample_rate: 16_000,
            channels: 1,
            payload: vec![0u8; 32],
        };
        runtime.ingest_chunks(&[chunk]).await;
        handle_voice_control(
            r#"{"op":"voice_interrupt","session":"s1"}"#,
            &voice,
            &runtime,
        )
        .await;
        let mut saw = false;
        for _ in 0..16 {
            match tokio::time::timeout(Duration::from_millis(50), rx.recv()).await {
                Ok(Ok(UiEvent::VoiceInterrupted { session, reason })) => {
                    if session == "s1" && reason == "operator_barge_in" {
                        saw = true;
                        break;
                    }
                }
                Ok(Ok(_)) => continue,
                _ => break,
            }
        }
        assert!(saw, "VoiceInterrupted must publish on voice_interrupt op");
    }

    #[tokio::test]
    async fn voice_stop_returns_session_id_for_owned_set_tracking() {
        // Audit closure: the WS handler tracks owned sessions and
        // drops them on disconnect. handle_voice_control must
        // signal which sessions it already closed so the disconnect
        // path doesn't double-end them.
        let bus = EventBus::new();
        let voice = VoiceSessionRegistry::new(bus.clone());
        let runtime = mock_runtime(bus);
        let result =
            handle_voice_control(r#"{"op":"voice_stop","session":"s99"}"#, &voice, &runtime).await;
        assert_eq!(result.as_deref(), Some("s99"));
    }

    #[tokio::test]
    async fn voice_interrupt_returns_none_so_owned_set_keeps_session() {
        let bus = EventBus::new();
        let voice = VoiceSessionRegistry::new(bus.clone());
        let runtime = mock_runtime(bus);
        let result = handle_voice_control(
            r#"{"op":"voice_interrupt","session":"s1"}"#,
            &voice,
            &runtime,
        )
        .await;
        assert_eq!(
            result, None,
            "interrupt does NOT close the session; the WS owned-set must keep it"
        );
    }

    #[tokio::test]
    async fn voice_stop_drop_guard_cleans_up_on_panic() {
        // Audit closure: panic-safety. Spawn a voice_stop and force
        // the spawned task to panic (we can't make the real
        // handle_voice_control panic without real Whisper, so
        // exercise the VoiceStopGuard directly).
        let bus = EventBus::new();
        let mut rx = bus.subscribe();
        let voice = VoiceSessionRegistry::new(bus.clone());
        let runtime = mock_runtime(bus);
        // Open a session through the registry so end_session has
        // something to drop.
        let header = crate::voice_frame::VoiceFrameHeader {
            session: "panic-victim".into(),
            seq: 0,
            codec: "pcm16le".into(),
            sample_rate: 16_000,
            channels: 1,
            ts_ms: None,
        };
        voice.observe_frame(&header, &[0u8; 32]).await;
        // Drop the guard inside a panicking task; the Drop impl
        // schedules cleanup on a fresh tokio task.
        let voice_clone = voice.clone();
        let runtime_clone = runtime.clone();
        let h = tokio::spawn(async move {
            let _guard = VoiceStopGuard {
                session_id: "panic-victim".into(),
                voice: voice_clone,
                runtime: runtime_clone,
            };
            panic!("simulated panic in finalize_utterance");
        });
        let _ = h.await; // collects the panic; task is detached

        // VoiceSessionEnded with reason=operator_stopped must fire
        // even though the parent task panicked.
        let mut saw = false;
        for _ in 0..32 {
            match tokio::time::timeout(Duration::from_millis(50), rx.recv()).await {
                Ok(Ok(UiEvent::VoiceSessionEnded { session, reason }))
                    if session == "panic-victim" && reason == "operator_stopped" =>
                {
                    saw = true;
                    break;
                }
                Ok(Ok(_)) => continue,
                _ => continue,
            }
        }
        assert!(
            saw,
            "VoiceStopGuard's Drop must publish VoiceSessionEnded even on panic"
        );
    }

    #[tokio::test]
    async fn voice_stop_op_finalizes_and_ends_session() {
        let bus = EventBus::new();
        let mut rx = bus.subscribe();
        let voice = VoiceSessionRegistry::new(bus.clone());
        let runtime = mock_runtime(bus);
        // Open the session via the registry path so the SPA-facing
        // VoiceSessionStarted/Ended sequence is real.
        let header = crate::voice_frame::VoiceFrameHeader {
            session: "s1".into(),
            seq: 0,
            codec: "pcm16le".into(),
            sample_rate: 16_000,
            channels: 1,
            ts_ms: None,
        };
        let outcome = voice.observe_frame(&header, &[0u8; 32]).await;
        runtime.ingest_chunks(&outcome.released).await;
        handle_voice_control(r#"{"op":"voice_stop","session":"s1"}"#, &voice, &runtime).await;
        // The voice_stop branch spawns a task; give it a moment.
        let mut saw_final_transcript = false;
        let mut saw_session_end = false;
        for _ in 0..50 {
            match tokio::time::timeout(Duration::from_millis(50), rx.recv()).await {
                Ok(Ok(UiEvent::VoiceTranscript { is_final, text, .. }))
                    if is_final && text == "transcribed!" =>
                {
                    saw_final_transcript = true;
                }
                Ok(Ok(UiEvent::VoiceSessionEnded { session, reason }))
                    if session == "s1" && reason == "operator_stopped" =>
                {
                    saw_session_end = true;
                }
                Ok(Ok(_)) => continue,
                _ => {}
            }
            if saw_final_transcript && saw_session_end {
                break;
            }
        }
        assert!(
            saw_final_transcript,
            "voice_stop must publish a final transcript"
        );
        assert!(saw_session_end, "voice_stop must end the registry session");
    }
}
